services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./moodle:/var/www/html:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - moodledata:/var/www/moodledata:rw
    depends_on:
      - php
      - db
    restart: unless-stopped

  php:
    build: .
    volumes:
      - ./moodle:/var/www/html:rw
      - moodledata:/var/www/moodledata:rw
    environment:
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=64M
      - POST_MAX_SIZE=64M
      - MAX_EXECUTION_TIME=600
      - PHP_MAX_INPUT_VARS=5000
    restart: unless-stopped

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: MoodlePass@123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data:
  moodledata: